#!/usr/bin/env python

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import  ActionChains

from pathlib import Path

def main():
    URL_PATH = str(Path.cwd()) + '\\AutoCheckOut\\URL.txt'
    with open(URL_PATH, 'r') as F:
        URL = F.readline()
    print(URL, type(URL))





if __name__ == '__main__':
    main()