#!/usr/bin/env python

from selenium.webdriver import Chrome
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import  ActionChains

from pathlib import Path

MAIN_PATH = str(Path.cwd()) + '\\AutoCheckOut'

class AutoCheckOut:
    def __init__(self):
        self.URL = str()
        self.CHECKOUT_XPATH = str()
        self.driver = Chrome(MAIN_PATH+ '\\chromedriver.exe')

        self.loadURL()
    def loadURL(self):
        with open(MAIN_PATH + '\\URL.txt', 'r') as F:
            self.URL = F.readline()
            self.URL = self.URL.strip('\n')
            self.CHECKOUT_XPATH = F.readline()
    def openURL(self):
        self.driver.get(self.URL)
    def test(self):
        print(self.URL)
        print(self.CHECKOUT_XPATH)

def main():
    aco = AutoCheckOut()
    aco.test()
    # aco.openURL()



if __name__ == '__main__':
    main()