#! /usr/bin/env python

from time import sleep

import login

URL_TEXT_DIRECTORY = 'URL.txt'
ID_TEXT_DIRECTORY = 'PASSWORD.txt'

def main():
    aco = login.AutoCheckOut(URL_TEXT_DIRECTORY, ID_TEXT_DIRECTORY)
    XPATH = aco.xPath()
    aco.openURL(XPATH)
    aco.login()
    while 1:
        sleep(1)
        
if __name__ == '__main__':
    main()