#! /usr/bin/env python
import sys
from time import sleep

import interface

URL_TEXT_DIRECTORY = 'URL.txt'
ID_TEXT_DIRECTORY = 'PASSWORD.txt'

def main():
    app = interface.QApplication(sys.argv)
    ui = interface.MainWindow(URL_TEXT_DIRECTORY, ID_TEXT_DIRECTORY)
    ui.timerOn()
    sys.exit(app.exec_())
        
if __name__ == '__main__':
    main()