#!/usr/bin/env python

import sys
sys.stdin = open('input.txt')

def myMax(lst):
    for idx in range(len(lst)):



N = int(input())
pillars = sorted([list(map(int, input().split())) for _ in range(N)])

a, b = max(pillars)

print(pillars)
print(a, b)