#!/usr/bin/env python

import sys
sys.stdin = open('input.txt')

def permu(i, N, temp):
    if i == N:
        if sum(temp) == 7:
            permutations.append(temp[:])
        return
    else:
        temp[i] = 0
        permu(i+1, N, temp)
        temp[i] = 1
        permu(i+1, N, temp)

dwarfs = [int(input()) for _ in range(9)]
permutations = list()
permu(0, 9, [0]*9)
real_dwarf = list()
for p in permutations:
    sum_tall = 0
    for i in range(9):
        sum_tall += p[i] * dwarfs[i]
    if sum_tall == 100:
        for i in range(9):
            if p[i] == 1:
                real_dwarf.append(dwarfs[i])

real_dwarf.sort()
for dwarf in real_dwarf:
    print(dwarf)

