#!/usr/bin/env python

fruit = int(input())
move = {key:list(map(int, input().split())) for key in range(6)}

move_max = [0, 0]
move_idx = [0, 0]
for i in range(6):
    m = move[i]
    if m[0] in [1,2]:
        if m[1] > move_max[0]:
            move_max[0] = m[1]
            move_idx[0] = i
    else:
        if m[1] > move_max[1]:
            move_max[1] = m[1]
            move_idx[1] = i
idx_set = set()
for i in [-1, 0, 1]:
    for idx in range(2):
        element = move_idx[idx]+i
        if element == -1:
            element = 5
        if element == 6:
            element = 0
        idx_set.add(element)

for idx in idx_set:
    del move[idx]
sub_space = []
for v in move.values():
    sub_space.append(v[1])
space = move_max[0] * move_max[1] - sub_space[0] * sub_space[1]

print(space*fruit)