#!/usr/bin/env python

N, K = map(int, input().split())
lst = list(map(int, input().split()))

sum_lst = sum(lst[:K])
max_sum = sum_lst
for i in range(N-K):
    ap = lst[i+K]
    de = lst[i]
    sum_lst += ap - de
    if sum_lst > max_sum:
        max_sum = sum_lst

print(max_sum)

# 21