#!/usr/bin/env python

import sys
sys.stdin = open('input.txt')

N = int(input())
white = [[0] * 100 for _ in range(100)]
for i in range(N):
    x, y = map(int, input().split())
    for row in range(x, x+10):
        white[row][y:y+10] = [1] * 10

area = 0
for w in white:
    area += sum(w)
print(area)
