#!/usr/bin/env python

def bingo(nums):
    count = 0
    for i in range(5):
        for j in range(5):
            if nums[i][j]:
                break
        else:
            count += 1
        for j in range(5):
            if nums[j][i]:
                break
        else:
            count += 1
    for i in range(5):
        if nums[i][i]:
            break
    else:
        count += 1
    for i in range(5):
        if nums[4-i][i]:
            break
    else:
        count += 1
    return count


my_bingo = [list(map(int, input().split())) for _ in range(5)]
numbers = [list(map(int, input().split())) for _ in range(5)]
counter = 0
bingos = 0
for number in numbers:
    for num in number:
        counter += 1
        for row in range(5):
            for col in range(5):
                if my_bingo[row][col] == num:
                    my_bingo[row][col] = 0
                    bingos = bingo(my_bingo)
                    break
            else:
                continue
            break
        if bingos > 2:
            break
    if bingos > 2:
        break
print(counter)
