#!/usr/bin/env python

first = int(input())
second = first
max_num = {'length': 0, 'number': []}

while second > first // 2:
    numbers = [first, second]
    second -= 1
    while True:
        next = numbers[-2] - numbers[-1]
        if next < 0:
            break
        numbers.append(next)
    if len(numbers) > max_num['length']:
        max_num['length'] = len(numbers)
        max_num['number'] = numbers

print(max_num['length'])
print(*max_num['number'])
