#!/usr/bin/env python

squares = [[0]*100 for _ in range(100)]
result = 0

for _ in range(4):
    startx, starty, endx, endy = map(int, input().split())
    for square in squares[starty:endy]:
        square[startx:endx] = [1] * len(square[startx:endx])
    
for square in squares:
    result += sum(square)

print(result)
